[tool.poetry]
name = "nh5"
version = "0.1.0"
description = "Safely evaluate simple Python programs"
authors = ["Jeremy Magland"]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/magland/safepyeval"
